1. What is a Python library? Why ^o we use Python libraries?

A Python library is a collection of pre-written code and functionalities that can be used by developers to perform common tasks without having to write the code from scratch. These libraries provide reusable modules and functions that can be easily imported and used in Python programs.

Python libraries serve several purposes:

Code Reusability: Libraries contain pre-written code that can be reused in different projects, saving time and effort. Developers can leverage the work of others to avoid reinventing the wheel.

Efficiency: Libraries are often optimized for performance and correctness. By using established libraries, developers can benefit from well-tested and efficient code, leading to faster development cycles.

Specialized Functionality: Many libraries are designed to provide specialized functionality in specific domains, such as data science, machine learning, web development, graphics, networking, and more. This allows developers to focus on solving higher-level problems without delving into the details of low-level implementation.

Community Collaboration: Python has a vibrant and active community that contributes to the development of various libraries. This collaborative effort leads to the creation of powerful tools and resources that can be freely shared and utilized by the community.

Standardization: Python libraries often adhere to standard conventions and coding practices. This helps in creating a consistent and standardized approach to solving common problems, promoting a more unified development ecosystem.

Popular Python libraries include NumPy for numerical computing, Pandas for data manipulation and analysis, TensorFlow and PyTorch for machine learning, Flask and Django for web development, Matplotlib and Seaborn for data visualization, and many more.

In summary, Python libraries enhance the capabilities of the language by providing pre-built solutions for various tasks, promoting code reuse, and fostering a collaborative and efficient development environment.

2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of items, but there are several key differences between them. Here are some of the main distinctions:

Data Type:

List: Python lists can contain elements of different data types. You can have a mix of integers, floats, strings, or even other lists within a single list.
NumPy Array: NumPy arrays are homogeneous, meaning all elements must be of the same data type. This uniformity allows for more efficient storage and operations on the array.
Performance:

List: Lists are more flexible but may be less efficient for numerical operations. Python lists are not optimized for numerical computations and lack built-in support for array operations.
NumPy Array: NumPy arrays are designed for numerical and scientific computations. They are implemented in C and allow for vectorized operations, making them significantly faster for numerical tasks compared to Python lists.
Memory Efficiency:

List: Lists are generally less memory-efficient compared to NumPy arrays due to their flexibility and overhead.
NumPy Array: NumPy arrays are more memory-efficient as they store data in contiguous blocks of memory and have a fixed, homogeneous data type.
Syntax and Ease of Use:

List: Lists are more versatile and have a more straightforward syntax. They are easy to work with for general-purpose tasks and do not require additional libraries.
NumPy Array: NumPy arrays require the NumPy library, and their syntax might be a bit more complex for beginners. However, they provide powerful tools for numerical operations.
Functionality:

List: Lists offer a broad range of general-purpose methods and functionalities.
NumPy Array: NumPy arrays provide specialized functions for mathematical and statistical operations, making them more suitable for scientific computing and data manipulation.

In [2]:
#example
# Using Python lists
python_list = [1, 2, 3, 4, 5]
python_list += [6, 7, 8]
print(python_list)

# Using NumPy arrays
import numpy as np
numpy_array = np.array([1, 2, 3, 4, 5])
numpy_array += 1
print(numpy_array)

[1, 2, 3, 4, 5, 6, 7, 8]
[2 3 4 5 6]


3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
import numpy as np

# Given array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Shape
shape_of_array = my_array.shape

# Size
size_of_array = my_array.size

# Dimension
dimension_of_array = my_array.ndim

# Printing the results
print("Shape of the array:", shape_of_array)
print("Size of the array:", size_of_array)
print("Dimension of the array:", dimension_of_array)


Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np

# Given array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Accessing the first row
first_row = my_array[0]

# Printing the result
print("First row of the array:", first_row)


First row of the array: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
import numpy as np

# Given array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Accessing the element at the third row and fourth column
element = my_array[2, 3]

# Printing the result
print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
import numpy as np

# Given array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Extracting all odd-indexed elements
odd_indexed_elements = my_array[:, 1::2]

# Printing the result
print("Odd-indexed elements from the array:")
print(odd_indexed_elements)


Odd-indexed elements from the array:
[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [7]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

# Print the generated matrix
print("Random 3x3 matrix:")
print(random_matrix)

Random 3x3 matrix:
[[0.96470993 0.22879139 0.53235495]
 [0.53437031 0.87783424 0.37144811]
 [0.04857062 0.84105628 0.22709546]]


8. Describe the difference between np.random.rand and np.random.randn?

In [ ]:
np.random.rand:

This function generates random numbers from a uniform distribution over the interval [0, 1).
The numbers produced are in the half-open interval [0, 1), meaning that 0 is included, but 1 is excluded.
It takes dimensions as arguments and returns an array of random values with the specified shape.
Example:
import numpy as np
# Generate a 2x2 matrix with random values between 0 and 1
random_matrix = np.random.rand(2, 2)
print(random_matrix)
                                                    
np.random.randn:

This function generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
The numbers produced follow a Gaussian distribution (bell-shaped curve) with a mean of 0 and a standard deviation of 1.
It also takes dimensions as arguments and returns an array of random values with the specified shape.
Example:

import numpy as np

# Generate a 2x2 matrix with random values from a standard normal distribution
random_matrix = np.random.randn(2, 2)
print(random_matrix)

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Increase the dimension along a new axis
new_dimension_array = original_array[:, :, np.newaxis]

# Print the original and new dimension arrays
print("Original Array:")
print(original_array)

print("\nArray with Increased Dimension:")
print(new_dimension_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with Increased Dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [9]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Increase the dimension along a new axis using np.expand_dims
new_dimension_array = np.expand_dims(original_array, axis=2)

# Print the original and new dimension arrays
print("Original Array:")
print(original_array)

print("\nArray with Increased Dimension:")
print(new_dimension_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with Increased Dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Transpose the array using .T
transposed_array = original_array.T

# Alternatively, you can use np.transpose()
# transposed_array = np.transpose(original_array)

# Print the original and transposed arrays
print("Original Array:")
print(original_array)

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
Perform the following operation using Python1
Index wiLe multiplicatio'
 Matix multiplicatio'
 Add both the maticK
Subtact matix B om 
Divide Matix B by A

In [12]:
#Matrix Multiplication (Dot Product):
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Matrix multiplication (dot product)
matrix_multiplication_result = np.dot(A, B.T)  # Transpose of B is used for proper dimensions

print("Matrix Multiplication Result:")
print(matrix_multiplication_result)


Matrix Multiplication Result:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [13]:
#Matrix Addition:
# Matrix addition
matrix_addition_result = A + B

print("\nMatrix Addition Result:")
print(matrix_addition_result)



Matrix Addition Result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [14]:
#Matrix Subtraction (Subtract Matrix B from A):
# Matrix subtraction
matrix_subtraction_result = A - B

print("\nMatrix Subtraction Result:")
print(matrix_subtraction_result)



Matrix Subtraction Result:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
#Matrix Division (Element-wise Division of Matrix B by A):
# Matrix division (element-wise division)
matrix_division_result = B / A

print("\nMatrix Division Result:")
print(matrix_division_result)



Matrix Division Result:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be use^ to swap the byte order of an array?

In [16]:
import numpy as np

# Create a sample array with 16-bit integers
original_array = np.array([1, 2, 3, 4], dtype=np.int16)

# Swap the byte order of the array
swapped_array = original_array.byteswap()

# Print the original and swapped arrays
print("Original Array:")
print(original_array)

print("\nSwapped Array:")
print(swapped_array)


Original Array:
[1 2 3 4]

Swapped Array:
[ 256  512  768 1024]


13. What is the significance of the np.linalg.inv function?

In [17]:
'''The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix.The inverse of a matrix is another matrix that, when multiplied with the original matrix, gives the identity matrix. In mathematical terms
'''
import numpy as np

# Create a square matrix A
A = np.array([[1, 2], [3, 4]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

print("Original Matrix A:")
print(A)

print("\nInverse of Matrix A:")
print(A_inv)


Original Matrix A:
[[1 2]
 [3 4]]

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]


14. What ^oes the np.reshape function ^o, an^ how is it use^?

In [18]:
import numpy as np

# Example 1: Reshaping a 1D array to a 2D array
arr1d = np.array([1, 2, 3, 4, 5, 6])
arr2d = np.reshape(arr1d, (2, 3))

print("Original 1D array:")
print(arr1d)

print("\nReshaped 2D array:")
print(arr2d)

# Example 2: Reshaping a 2D array to a 1D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.reshape(arr2d, (6,))

print("\nOriginal 2D array:")
print(arr2d)

print("\nReshaped 1D array:")
print(arr1d)


Original 1D array:
[1 2 3 4 5 6]

Reshaped 2D array:
[[1 2 3]
 [4 5 6]]

Original 2D array:
[[1 2 3]
 [4 5 6]]

Reshaped 1D array:
[1 2 3 4 5 6]


15. What is broa^casting in Numpy?

In [19]:
import numpy as np

# Example 1: Broadcasting a scalar to an array
scalar_value = 5
array = np.array([1, 2, 3, 4])

result = scalar_value * array  # The scalar is broadcasted to match the shape of the array

print("Result of broadcasting a scalar:")
print(result)

# Example 2: Broadcasting between two arrays
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([10, 20, 30])

result = array_a + array_b  # The 1D array is broadcasted to match the shape of the 2D array

print("\nResult of broadcasting between two arrays:")
print(result)


Result of broadcasting a scalar:
[ 5 10 15 20]

Result of broadcasting between two arrays:
[[11 22 33]
 [14 25 36]]
